### ISSUE TITLE
How to view a label

### ISSUE THREAD

**Issue by SarahH20** [Gomah/sendle-node#1]
Hi,
Thanks for sharing codes in node js to create and cancel order. Could you please share code to view a Sendle label using node js? Thanks for your help.

**Comment by Gomah** [comment]
Hey @SarahH20, just updated the client to support labels:

```ts
const orderId = 'f5233746-71d4-4b05-bf63-56f4abaed5f6';
const size = 'a4'; // Available optins: 'a4', 'cropped' or 'letter' (US).

const label = await client.labels.get({
  orderId,
  size, // default 'a4'
});
```

Also added some documentation around it: https://sendle-node.vercel.app/label

Let me know if it helps!

**Comment by SarahH20** [comment]
Thank you for your help. I tried this code and got some data response back (not the pdf file though, probably because I need to save it somewhere in order to view it?). Is there any way to direct users directly to Sendle page/ website to download the label and we don't have to store this label on our server? Thanks again for your help!

**Comment by Gomah** [comment]
> Thank you for your help. I tried this code and got some data response back (not the pdf file though, probably because I need to save it somewhere in order to view it?). Is there any way to direct users directly to Sendle page/ website to download the label and we don't have to store this label on our server? Thanks again for your help!

If you look at this example: https://sendle-node.vercel.app/label#usage-in-real-world-application

You can add a `Content-disposition` header before returning the pdf to enforce your users to download the label, e.g:

```ts
reply.header('Content-disposition', `attachment; filename=${shipmentId}`);
```

**Comment by SarahH20** [comment]
> > Thank you for your help. I tried this code and got some data response back (not the pdf file though, probably because I need to save it somewhere in order to view it?). Is there any way to direct users directly to Sendle page/ website to download the label and we don't have to store this label on our server? Thanks again for your help!
> 
> If you look at this example: https://sendle-node.vercel.app/label#usage-in-real-world-application
> 
> You can add a `Content-disposition` header before returning the pdf to enforce your users to download the label, e.g:
> 
> ```ts
> reply.header('Content-disposition', `attachment; filename=${shipmentId}`);
> ```

Thank you for your help, Gomah.
