### ISSUE TITLE
How to update the HTTP User-Agent header?

### ISSUE THREAD

**Issue by SarahH20** [Gomah/sendle-node#2]
Hi,

I'd like to update the HTTP User-Agent header with our app reference information (e.g. refAABB123) so that Sendle can recognise our app more easily. Can I update our reference number in the client below? Could you advise how to do so? An example would be extremely helpful. Thank you for your help!

const client = new SendleClient({
  sendleId: 'yourSendleId',
  apiKey: 'yourApiKey',
  sandbox: true, // default to false
  gotOptions: {},
});

Sarah

**Comment by Gomah** [comment]
You can leverage the `gotOptions` parameter here, see [`User Agent`](https://github.com/sindresorhus/got#user-agent):


```ts
import { SendleClient } from 'sendle-node';

const client = new SendleClient({
  sendleId: process.env.SENDLE_USERNAME,
  apiKey: process.env.SENDLE_API_KEY,
  sandbox: process.env.APPLICATION_ENVIRONMENT !== 'production',
  gotOptions: {
    headers: {
      'user-agent': 'refAABB123',
    },
  },
});
```

Note: By default the `user-agent` is set to `sendle-node/${package.version}`: `sendle-node/1.1.1`.

**Comment by SarahH20** [comment]
> You can leverage the `gotOptions` parameter here, see [`User Agent`](https://github.com/sindresorhus/got#user-agent):
> 
> ```ts
> import { SendleClient } from 'sendle-node';
> 
> const client = new SendleClient({
>   sendleId: process.env.SENDLE_USERNAME,
>   apiKey: process.env.SENDLE_API_KEY,
>   sandbox: process.env.APPLICATION_ENVIRONMENT !== 'production',
>   gotOptions: {
>     headers: {
>       'user-agent': 'refAABB123',
>     },
>   },
> });
> ```
> 
> Note: By default the `user-agent` is set to `sendle-node/${package.version}`: `sendle-node/1.1.1`.

Thank you for your help!
